language: ruby

dist: xenial

cache:
  bundler: true

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.1
  - jruby-9.2
  - jruby-head
  - ruby-head
  - rubinius-3
  - rubinius-4

matrix:
  allow_failures:
    - rvm: jruby-9.1
    - rvm: jruby-9.2
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius-3
    - rvm: rubinius-4

branches:
  only:
    - master
    - auto-update-dependencies
