sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.7.0
  - jruby-head
  - ruby-head
  - rubinius-3
matrix:
  allow_failures:
    - rvm: jruby-9.1.7.0
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius-3
script: "bundle exec rake"
branches:
  only:
    - master
